In [15]:
import numpy as np

def main():
    u = np.array([7,3,5])
    print(u)
    print()
    
    # get size of vector
    print("length of vector: ", len(u))
    print("norm of vector: ", np.linalg.norm(u))
    
    # define matrix
    A = np.matrix([[4,9,2], [3,5,7], [8,1,6]])
    print(A)
    print("norm of A: ", np.linalg.norm(A))
    print("shape of A:", A.shape)
    print("rows of A: ", A.shape[0])
    print("columns of A: ", A.shape[1])
    print()
    
    # transpose of matrix
    W = A.transpose()
    print("transpose of A: \n", W)
    print()
    
    # matrix multiply
    Q = W * A
    print("W * A: \n", Q)
    print()
    
    # dot product
    u = np.array([4,9,2])
    v = np.array([3,5,7])
    
    print(u)
    print(v)
    w = np.dot(u,v)
    print("dot product of u and v: ", w)
    print()
    
    # cross product
    w = np.cross(u,v)
    print("cross product of u and v: ", w)
    q = np.cross(v,u)
    print("cross product of v and u: ", q)
    
    '''
    stretch vertically
    A = [[k,0],[0,1]]
    # shear 
    A = [[1,k],[0,1]]
    # rotation (no eigenvalue/vector)
    A = [[cos(x),sin(x)],[-sin(x),cos(x)]]
    
    
    '''

main()

[7 3 5]

length of vector:  3
norm of vector:  9.1104335791443
[[4 9 2]
 [3 5 7]
 [8 1 6]]
norm of A:  16.881943016134134
shape of A: (3, 3)
rows of A:  3
columns of A:  3

transpose of A: 
 [[4 3 8]
 [9 5 1]
 [2 7 6]]

W * A: 
 [[ 89  59  77]
 [ 59 107  59]
 [ 77  59  89]]

[4 9 2]
[3 5 7]
dot product of u and v:  71

cross product of u and v:  [ 53 -22  -7]
cross product of v and u:  [-53  22   7]


In [ ]:
from vpython import *

def main():
    G = 6.67408e-11
    #kg
    mSun = 1.9891e30
    #radius of the sun not to scale (6.69634e8 meters)
    rSun = 5e10
    
    mEarth = 5.972e24
    #radius of the Earth not to scale (6.367e6 meters)
    rEarth = 1e10
    
    #create sun and Earth objects
    sun = sphere(pos=vector(0,0,0), radius=rSun, color=color.yellow)
    Earth = sphere(pos=vector(1.496e11,0,0), radius=rEarth, color=color.blue, make_trail=True)
    
    Earth.velocity = vector(0,3e4,0)
    
    #define time
    t = 0
    dt = 3600
    
    while(t < 1e10):
        rate(3000)
        Earth.pos = Earth.pos + Earth.velocity * dt
        rVector = Earth.pos - sun.pos
        fGrav = - (G * mSun * mEarth) / (mag(rVector)**2) * (norm(rVector))
        Earth.velocity = Earth.velocity + fGrav/mEarth * dt
        t = t + dt
        
main()